name: my_vision
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.3
  flutter_vision: ^1.0.1
  image_picker: ^0.8.6+1
  http: ^0.13.5
  dio: ^4.0.6
  flutter_image_compress: ^1.1.3
  image: ^4.0.15
  path_provider: ^2.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
